---

- name: Add backup system user
  user: name={{ rsnapshot_slave_user }} shell={{ rsnapshot_slave_user_shell }}
        update_password=on_create

- name: Sudo configuration for the backup system user
  template: src=sudo_backupuser dest=/etc/sudoers.d/{{ rsnapshot_slave_user }}
            owner=root group=root mode=0440
  when: ansible_os_family == "Debian" and ansible_lsb.major_release|int >= 6

# Put SSH relative tasks in another file to bypass the Ansible bug #15746:
#   https://github.com/ansible/ansible/issues/15746
# ('delegate_to' statement is evaluated before 'when')
- include_tasks: config_ssh.yml
  when: rsnapshot_master_host and rsnapshot_master_host_user
